version: "3"

services:
  web:
    build: .
    image: takacsmark/swarm-example:1.0
    ports:
      - 80:3000
    networks:
      - mynet
  db:
       image: mongo:4.0.3
       networks:
       - mynet
       

networks:
  mynet: